# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'commentmanagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CommentManagementWindow(object):
    def setupUi(self, CommentManagementWindow):
        CommentManagementWindow.setObjectName("CommentManagementWindow")
        CommentManagementWindow.resize(800, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CommentManagementWindow.sizePolicy().hasHeightForWidth())
        CommentManagementWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(CommentManagementWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.commentLabel = QtWidgets.QLabel(self.centralwidget)
        self.commentLabel.setObjectName("commentLabel")
        self.verticalLayout.addWidget(self.commentLabel)
        self.commenttable = QtWidgets.QTableWidget(self.centralwidget)
        self.commenttable.setRowCount(17)
        self.commenttable.setColumnCount(5)
        self.commenttable.setObjectName("commenttable")
        self.verticalLayout.addWidget(self.commenttable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        self.AddCommentButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddCommentButton.sizePolicy().hasHeightForWidth())
        self.AddCommentButton.setSizePolicy(sizePolicy)
        self.AddCommentButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddCommentButton.setObjectName("AddCommentButton")
        self.buttonLayout.addWidget(self.AddCommentButton)
        self.backToMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToMainButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToMainButton.setObjectName("backToMainButton")
        self.buttonLayout.addWidget(self.backToMainButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        CommentManagementWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(CommentManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(CommentManagementWindow)

    def retranslateUi(self, CommentManagementWindow):
        _translate = QtCore.QCoreApplication.translate
        CommentManagementWindow.setStyleSheet(_translate("CommentManagementWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}"))
        self.commentLabel.setText(_translate("CommentManagementWindow", "所有评论"))
        self.AddCommentButton.setText(_translate("CommentManagementWindow", "添加评论"))
        self.backToMainButton.setText(_translate("CommentManagementWindow", "返回主界面"))
