# 此类已废弃
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eluosi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import subprocess
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(426, 300)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003D79;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 120, 172, 106))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 10, 241, 121))
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_2.setText(_translate("Form", "开始游戏"))
        self.pushButton.setText(_translate("Form", "返回主菜单"))
        self.label.setText(_translate("Form", "# 俄罗斯方块"))
class EluosiWindow(QtWidgets.QWidget):  # 你可以根据需要选择 QWidget 或 QMainWindow
    def __init__(self):
        super().__init__()
        self.ui = Ui_Form()  # 引入生成的 UI 类
        self.ui.setupUi(self)  # 将 UI 设置到当前窗口

        # 连接按钮事件
        self.ui.pushButton_2.clicked.connect(self.start_game)  # 开始游戏按钮
        self.ui.pushButton.clicked.connect(self.back_to_menu)  # 返回主菜单按钮

    def start_game(self):
        print("开始游戏！")  # 打印调试信息

        # 获取当前目录
        current_directory = sys.path[0]  # 获取当前 Python 脚本的目录

        # 设置运行的可执行文件路径
        executable = f"{current_directory}/eluosi.exe"  # 如果是 Windows 上可能是 eluosi.exe

        # 使用 subprocess 启动命令行中的程序，确保启动独立的命令提示符窗口
        try:
            # 启动新的命令提示符窗口，并在其中运行游戏
            # 使用 'chcp 65001' 命令设置编码为 UTF-8
            subprocess.Popen(['cmd', '/C', 'start', 'cmd', '/K', 'chcp 65001 && ' + executable])
            print("游戏已启动！")
        except Exception as e:
            print(f"无法启动游戏: {e}")

    def back_to_menu(self):
        print("返回主菜单！")# 在此可以实现返回主菜单的逻辑，或者关闭当前窗口
        print("返回主菜单！")  # 打印调试信息，实际功能可以在这里实现
        self.close()  # 关闭当前游戏窗口（俄罗斯方块窗口）

        # 这里你可以实例化并显示主菜单窗口
        # self.main_menu_window = MainInterface()  # 创建主菜单窗口的实例
        # self.main_menu_window.show()  # 显示主菜单窗口