# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_privileges(object):
    def setupUi(self, admin_privileges):
        admin_privileges.setObjectName("admin_privileges")
        admin_privileges.resize(770, 597)
        self.centralwidget = QtWidgets.QWidget(admin_privileges)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.horizontalLayout, 12, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 7, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 11, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 10, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.searchreasult = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchreasult.sizePolicy().hasHeightForWidth())
        self.searchreasult.setSizePolicy(sizePolicy)
        self.searchreasult.setObjectName("searchreasult")
        self.searchreasult.setColumnCount(6)
        self.searchreasult.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.searchreasult.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchreasult.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchreasult.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchreasult.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchreasult.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.searchreasult.setHorizontalHeaderItem(5, item)
        self.gridLayout.addWidget(self.searchreasult, 0, 1, 12, 1)
        admin_privileges.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(admin_privileges)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 770, 22))
        self.menubar.setObjectName("menubar")
        admin_privileges.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(admin_privileges)
        self.statusbar.setObjectName("statusbar")
        admin_privileges.setStatusBar(self.statusbar)

        self.retranslateUi(admin_privileges)
        QtCore.QMetaObject.connectSlotsByName(admin_privileges)

    def retranslateUi(self, admin_privileges):
        _translate = QtCore.QCoreApplication.translate
        admin_privileges.setWindowTitle(_translate("admin_privileges", "MainWindow"))
        admin_privileges.setStyleSheet(_translate("admin_privileges", "\n"
"    QMainWindow {\n"
"        background-color: #F5F5F5;\n"
"        font-family: \'Segoe UI\', sans-serif;\n"
"    }\n"
"\n"
"    QPushButton {\n"
"        background-color: #0078D7;\n"
"        border: none;\n"
"        border-radius: 4px;\n"
"        color: white;\n"
"        padding: 10px;\n"
"        min-width: 150px;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: #005FAC;\n"
"    }\n"
"\n"
"    QLabel {\n"
"        font-size: 16px;\n"
"        font-weight: bold;\n"
"        color: #333;\n"
"    }\n"
"\n"
"    QTextEdit {\n"
"        border: 1px solid #ccc;\n"
"        font-size: 14px;\n"
"        color: #333;\n"
"        padding: 10px;\n"
"    }\n"
"\n"
"    QTableWidget {\n"
"        border: 1px solid #ccc;\n"
"        font-size: 14px;\n"
"        color: #333;\n"
"    }\n"
"\n"
"    QTableWidget::item {\n"
"        padding: 5px;\n"
"        border-bottom: 1px solid #ccc;\n"
"    }\n"
"\n"
"    QTableWidget::horizontalHeader {\n"
"        background-color: #0078D7;\n"
"        color: white;\n"
"    }\n"
"   "))
        self.pushButton_4.setText(_translate("admin_privileges", "刷新"))
        self.pushButton.setText(_translate("admin_privileges", "添加"))
        self.pushButton_2.setText(_translate("admin_privileges", "删除"))
        self.pushButton_3.setText(_translate("admin_privileges", "离开"))
        self.label.setText(_translate("admin_privileges", "请输入航班的编号"))
        self.label_2.setText(_translate("admin_privileges", "请输入离开时间"))
        self.label_4.setText(_translate("admin_privileges", "请输入起点"))
        self.label_3.setText(_translate("admin_privileges", "请输入到达时间"))
        self.label_6.setText(_translate("admin_privileges", "请输入航空公司名称"))
        self.label_5.setText(_translate("admin_privileges", "请输入目的地"))
        item = self.searchreasult.horizontalHeaderItem(0)
        item.setText(_translate("admin_privileges", "编号"))
        item = self.searchreasult.horizontalHeaderItem(1)
        item.setText(_translate("admin_privileges", "离开时间"))
        item = self.searchreasult.horizontalHeaderItem(2)
        item.setText(_translate("admin_privileges", "到达时间"))
        item = self.searchreasult.horizontalHeaderItem(3)
        item.setText(_translate("admin_privileges", "起点"))
        item = self.searchreasult.horizontalHeaderItem(4)
        item.setText(_translate("admin_privileges", "目的地"))
        item = self.searchreasult.horizontalHeaderItem(5)
        item.setText(_translate("admin_privileges", "航司"))
