# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlightDetailsWindow(object):
    def setupUi(self, FlightDetailsWindow):
        FlightDetailsWindow.setObjectName("FlightDetailsWindow")
        FlightDetailsWindow.resize(800, 602)
        self.centralwidget = QtWidgets.QWidget(FlightDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flightDetailsLabel = QtWidgets.QLabel(self.centralwidget)
        self.flightDetailsLabel.setObjectName("flightDetailsLabel")
        self.verticalLayout.addWidget(self.flightDetailsLabel)
        self.flightInfoLayout = QtWidgets.QVBoxLayout()
        self.flightInfoLayout.setObjectName("flightInfoLayout")
        self.flightNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.flightNumberLabel.setObjectName("flightNumberLabel")
        self.flightInfoLayout.addWidget(self.flightNumberLabel)
        self.airlineLabel = QtWidgets.QLabel(self.centralwidget)
        self.airlineLabel.setObjectName("airlineLabel")
        self.flightInfoLayout.addWidget(self.airlineLabel)
        self.departureTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.departureTimeLabel.setObjectName("departureTimeLabel")
        self.flightInfoLayout.addWidget(self.departureTimeLabel)
        self.arrivalTimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.arrivalTimeLabel.setObjectName("arrivalTimeLabel")
        self.flightInfoLayout.addWidget(self.arrivalTimeLabel)
        self.verticalLayout.addLayout(self.flightInfoLayout)
        self.seatsInfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.seatsInfoLabel.setObjectName("seatsInfoLabel")
        self.verticalLayout.addWidget(self.seatsInfoLabel)
        self.seatsTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.seatsTableWidget.setColumnCount(4)
        self.seatsTableWidget.setProperty("horizontalHeaderLabels", ['座位类型', '空余座位', '单价', '总价'])
        self.seatsTableWidget.setObjectName("seatsTableWidget")
        self.seatsTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.seatsTableWidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.backToPreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToPreviousButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToPreviousButton.setObjectName("backToPreviousButton")
        self.buttonLayout.addWidget(self.backToPreviousButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        FlightDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FlightDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(FlightDetailsWindow)

    def retranslateUi(self, FlightDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        FlightDetailsWindow.setStyleSheet(_translate("FlightDetailsWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}"))
        self.flightDetailsLabel.setText(_translate("FlightDetailsWindow", "航班详情"))
        self.flightNumberLabel.setText(_translate("FlightDetailsWindow", "航班号: ABC123"))
        self.airlineLabel.setText(_translate("FlightDetailsWindow", "航空公司: XYZ Airlines"))
        self.departureTimeLabel.setText(_translate("FlightDetailsWindow", "出发时间: 2024-12-20 10:00"))
        self.arrivalTimeLabel.setText(_translate("FlightDetailsWindow", "到达时间: 2024-12-20 14:00"))
        self.seatsInfoLabel.setText(_translate("FlightDetailsWindow", "空余座位和价格："))
        self.pushButton.setText(_translate("FlightDetailsWindow", "下订单"))
        self.backToPreviousButton.setText(_translate("FlightDetailsWindow", "返回主菜单"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FlightDetailsWindow = QtWidgets.QMainWindow()
    ui = Ui_FlightDetailsWindow()
    ui.setupUi(FlightDetailsWindow)
    FlightDetailsWindow.show()
    sys.exit(app.exec_())