# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_recommendation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlightRecommendationWindow(object):
    def setupUi(self, FlightRecommendationWindow):
        FlightRecommendationWindow.setObjectName("FlightRecommendationWindow")
        FlightRecommendationWindow.resize(800, 602)
        self.centralwidget = QtWidgets.QWidget(FlightRecommendationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.recommendationLabel = QtWidgets.QLabel(self.centralwidget)
        self.recommendationLabel.setObjectName("recommendationLabel")
        self.verticalLayout.addWidget(self.recommendationLabel)
        self.locationLayout = QtWidgets.QHBoxLayout()
        self.locationLayout.setSpacing(10)
        self.locationLayout.setObjectName("locationLayout")
        self.departureLabel = QtWidgets.QLabel(self.centralwidget)
        self.departureLabel.setObjectName("departureLabel")
        self.locationLayout.addWidget(self.departureLabel)
        self.departureComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.departureComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.departureComboBox.setObjectName("departureComboBox")
        self.locationLayout.addWidget(self.departureComboBox)
        self.destinationLabel = QtWidgets.QLabel(self.centralwidget)
        self.destinationLabel.setObjectName("destinationLabel")
        self.locationLayout.addWidget(self.destinationLabel)
        self.destinationComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.destinationComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.destinationComboBox.setObjectName("destinationComboBox")
        self.locationLayout.addWidget(self.destinationComboBox)
        self.findFlightsButton = QtWidgets.QPushButton(self.centralwidget)
        self.findFlightsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.findFlightsButton.setObjectName("findFlightsButton")
        self.locationLayout.addWidget(self.findFlightsButton)
        self.verticalLayout.addLayout(self.locationLayout)
        self.criteriaLabel = QtWidgets.QLabel(self.centralwidget)
        self.criteriaLabel.setObjectName("criteriaLabel")
        self.verticalLayout.addWidget(self.criteriaLabel)
        self.criteriaLayout = QtWidgets.QVBoxLayout()
        self.criteriaLayout.setObjectName("criteriaLayout")
        self.seasonCriteria = QtWidgets.QLabel(self.centralwidget)
        self.seasonCriteria.setObjectName("seasonCriteria")
        self.criteriaLayout.addWidget(self.seasonCriteria)
        self.airlineCriteria = QtWidgets.QLabel(self.centralwidget)
        self.airlineCriteria.setObjectName("airlineCriteria")
        self.criteriaLayout.addWidget(self.airlineCriteria)
        self.dateCriteria = QtWidgets.QLabel(self.centralwidget)
        self.dateCriteria.setObjectName("dateCriteria")
        self.criteriaLayout.addWidget(self.dateCriteria)
        self.directTransitCriteria = QtWidgets.QLabel(self.centralwidget)
        self.directTransitCriteria.setObjectName("directTransitCriteria")
        self.criteriaLayout.addWidget(self.directTransitCriteria)
        self.verticalLayout.addLayout(self.criteriaLayout)
        self.flightsTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.flightsTableWidget.setColumnCount(5)
        self.flightsTableWidget.setProperty("horizontalHeaderLabels", ['航班号', '航空公司', '出发时间', '到达时间', '票价'])
        self.flightsTableWidget.setObjectName("flightsTableWidget")
        self.flightsTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.flightsTableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.backToMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToMainButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToMainButton.setObjectName("backToMainButton")
        self.buttonLayout.addWidget(self.backToMainButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        FlightRecommendationWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FlightRecommendationWindow)
        QtCore.QMetaObject.connectSlotsByName(FlightRecommendationWindow)

    def retranslateUi(self, FlightRecommendationWindow):
        _translate = QtCore.QCoreApplication.translate
        FlightRecommendationWindow.setStyleSheet(_translate("FlightRecommendationWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #ccc;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}"))
        self.recommendationLabel.setText(_translate("FlightRecommendationWindow", "航班比价推荐"))
        self.departureLabel.setText(_translate("FlightRecommendationWindow", "出发地："))
        self.departureComboBox.setPlaceholderText(_translate("FlightRecommendationWindow", "选择出发地"))
        self.destinationLabel.setText(_translate("FlightRecommendationWindow", "目的地："))
        self.destinationComboBox.setPlaceholderText(_translate("FlightRecommendationWindow", "选择目的地"))
        self.findFlightsButton.setText(_translate("FlightRecommendationWindow", "查找航班"))
        self.criteriaLabel.setText(_translate("FlightRecommendationWindow", "航班推荐依据："))
        self.seasonCriteria.setText(_translate("FlightRecommendationWindow", "淡旺季数据：依据目的地的季节性需求，推荐合适的航班时间。"))
        self.airlineCriteria.setText(_translate("FlightRecommendationWindow", "航空公司选择：根据用户的航空公司偏好，显示不同航空公司的航班。"))
        self.dateCriteria.setText(_translate("FlightRecommendationWindow", "日期出行数据：推荐基于当前日期的航班情况，适合出行的日期和航班。"))
        self.directTransitCriteria.setText(_translate("FlightRecommendationWindow", "直达与中转：提供直达与中转的选择依据，适应不同的时间和预算。"))
        self.backToMainButton.setText(_translate("FlightRecommendationWindow", "返回主界面"))
