# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlightDetailsWindow(object):
    def setupUi(self, FlightDetailsWindow):
        FlightDetailsWindow.setObjectName("FlightDetailsWindow")
        FlightDetailsWindow.resize(608, 437)
        self.centralwidget = QtWidgets.QWidget(FlightDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.flightDetailsLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flightDetailsLabel.sizePolicy().hasHeightForWidth())
        self.flightDetailsLabel.setSizePolicy(sizePolicy)
        self.flightDetailsLabel.setObjectName("flightDetailsLabel")
        self.verticalLayout.addWidget(self.flightDetailsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.flightNumberLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flightNumberLabel.sizePolicy().hasHeightForWidth())
        self.flightNumberLabel.setSizePolicy(sizePolicy)
        self.flightNumberLabel.setObjectName("flightNumberLabel")
        self.horizontalLayout.addWidget(self.flightNumberLabel)
        self.id = QtWidgets.QLabel(self.centralwidget)
        self.id.setObjectName("id")
        self.horizontalLayout.addWidget(self.id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.airlineLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.airlineLabel.sizePolicy().hasHeightForWidth())
        self.airlineLabel.setSizePolicy(sizePolicy)
        self.airlineLabel.setObjectName("airlineLabel")
        self.horizontalLayout_2.addWidget(self.airlineLabel)
        self.company = QtWidgets.QLabel(self.centralwidget)
        self.company.setObjectName("company")
        self.horizontalLayout_2.addWidget(self.company)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.departureTimeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departureTimeLabel.sizePolicy().hasHeightForWidth())
        self.departureTimeLabel.setSizePolicy(sizePolicy)
        self.departureTimeLabel.setObjectName("departureTimeLabel")
        self.horizontalLayout_3.addWidget(self.departureTimeLabel)
        self.depaturetime = QtWidgets.QLabel(self.centralwidget)
        self.depaturetime.setObjectName("depaturetime")
        self.horizontalLayout_3.addWidget(self.depaturetime)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.price = QtWidgets.QLabel(self.centralwidget)
        self.price.setObjectName("price")
        self.horizontalLayout_4.addWidget(self.price)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.arrivalTimeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrivalTimeLabel.sizePolicy().hasHeightForWidth())
        self.arrivalTimeLabel.setSizePolicy(sizePolicy)
        self.arrivalTimeLabel.setObjectName("arrivalTimeLabel")
        self.horizontalLayout_5.addWidget(self.arrivalTimeLabel)
        self.arrivaltime = QtWidgets.QLabel(self.centralwidget)
        self.arrivaltime.setObjectName("arrivaltime")
        self.horizontalLayout_5.addWidget(self.arrivaltime)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.buttonLayout.addWidget(self.pushButton)
        self.backToPreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToPreviousButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToPreviousButton.setObjectName("backToPreviousButton")
        self.buttonLayout.addWidget(self.backToPreviousButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        FlightDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FlightDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(FlightDetailsWindow)

    def retranslateUi(self, FlightDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        FlightDetailsWindow.setStyleSheet(_translate("FlightDetailsWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}"))
        self.flightDetailsLabel.setText(_translate("FlightDetailsWindow", "航班详情"))
        self.flightNumberLabel.setText(_translate("FlightDetailsWindow", "航班号: "))
        self.id.setText(_translate("FlightDetailsWindow", "id"))
        self.airlineLabel.setText(_translate("FlightDetailsWindow", "航空公司: "))
        self.company.setText(_translate("FlightDetailsWindow", "company"))
        self.departureTimeLabel.setText(_translate("FlightDetailsWindow", "出发时间: "))
        self.depaturetime.setText(_translate("FlightDetailsWindow", "de"))
        self.label.setText(_translate("FlightDetailsWindow", "票价："))
        self.price.setText(_translate("FlightDetailsWindow", "pr"))
        self.arrivalTimeLabel.setText(_translate("FlightDetailsWindow", "到达时间: "))
        self.arrivaltime.setText(_translate("FlightDetailsWindow", "ar"))
        self.pushButton.setText(_translate("FlightDetailsWindow", "下订单"))
        self.backToPreviousButton.setText(_translate("FlightDetailsWindow", "返回主菜单"))
