# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.vboxlayout.addWidget(self.titleLabel)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        self.tabWidget.setObjectName("tabWidget")
        self.loginTab = QtWidgets.QWidget()
        self.loginTab.setObjectName("loginTab")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.loginTab)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.usernameLogin = QtWidgets.QLineEdit(self.loginTab)
        self.usernameLogin.setObjectName("usernameLogin")
        self.vboxlayout1.addWidget(self.usernameLogin)
        self.passwordLogin = QtWidgets.QLineEdit(self.loginTab)
        self.passwordLogin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLogin.setObjectName("passwordLogin")
        self.vboxlayout1.addWidget(self.passwordLogin)
        self.loginButton = QtWidgets.QPushButton(self.loginTab)
        self.loginButton.setObjectName("loginButton")
        self.vboxlayout1.addWidget(self.loginButton)
        self.tabWidget.addTab(self.loginTab, "")
        self.registerTab = QtWidgets.QWidget()
        self.registerTab.setObjectName("registerTab")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.registerTab)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.usernameRegister = QtWidgets.QLineEdit(self.registerTab)
        self.usernameRegister.setObjectName("usernameRegister")
        self.vboxlayout2.addWidget(self.usernameRegister)
        self.passwordRegister = QtWidgets.QLineEdit(self.registerTab)
        self.passwordRegister.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordRegister.setObjectName("passwordRegister")
        self.vboxlayout2.addWidget(self.passwordRegister)
        self.phoneRegister = QtWidgets.QLineEdit(self.registerTab)
        self.phoneRegister.setObjectName("phoneRegister")
        self.vboxlayout2.addWidget(self.phoneRegister)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.registerTab)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.vboxlayout2.addWidget(self.lineEdit_2)
        self.emailRegister = QtWidgets.QLineEdit(self.registerTab)
        self.emailRegister.setObjectName("emailRegister")
        self.vboxlayout2.addWidget(self.emailRegister)
        self.registerButton = QtWidgets.QPushButton(self.registerTab)
        self.registerButton.setObjectName("registerButton")
        self.vboxlayout2.addWidget(self.registerButton)
        self.cancelButton = QtWidgets.QPushButton(self.registerTab)
        self.cancelButton.setObjectName("cancelButton")
        self.vboxlayout2.addWidget(self.cancelButton)
        self.tabWidget.addTab(self.registerTab, "")
        self.vboxlayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "机票管理系统"))
        self.titleLabel.setText(_translate("MainWindow", "机票管理系统 ✈️"))
        self.titleLabel.setStyleSheet(_translate("MainWindow", "font-size: 26px; font-weight: bold; color: #2c3e50; margin-top: 30px;"))
        self.usernameLogin.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.usernameLogin.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 12px; font-size: 16px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 15px;"))
        self.passwordLogin.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.passwordLogin.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 12px; font-size: 16px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 25px;"))
        self.loginButton.setText(_translate("MainWindow", "登录 🚀"))
        self.loginButton.setStyleSheet(_translate("MainWindow", "\n"
"            background-color: #3498db;\n"
"            color: white;\n"
"            border-radius: 12px;\n"
"            font-size: 18px;\n"
"            padding: 18px;\n"
"            border: none;\n"
"            margin-top: 20px;\n"
"            box-shadow: 0 4px 8px rgba(52, 152, 219, 0.3);\n"
"           "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.loginTab), _translate("MainWindow", "登录"))
        self.usernameRegister.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.usernameRegister.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 10px; font-size: 14px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 10px;"))
        self.passwordRegister.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.passwordRegister.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 10px; font-size: 14px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 10px;"))
        self.phoneRegister.setPlaceholderText(_translate("MainWindow", "请输入手机号"))
        self.phoneRegister.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 10px; font-size: 14px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 10px;"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入身份证号"))
        self.lineEdit_2.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 10px; font-size: 14px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 10px;"))
        self.emailRegister.setPlaceholderText(_translate("MainWindow", "请输入邮箱"))
        self.emailRegister.setStyleSheet(_translate("MainWindow", "border-radius: 8px; padding: 10px; font-size: 14px; background-color: #ecf0f1; border: 1px solid #bdc3c7; margin-bottom: 25px;"))
        self.registerButton.setText(_translate("MainWindow", "注册 ✨"))
        self.registerButton.setStyleSheet(_translate("MainWindow", "background-color: #3498db; color: white; border-radius: 8px; font-size: 16px; padding: 12px; border: none; margin-top: 10px;"))
        self.cancelButton.setText(_translate("MainWindow", "取消 ❌"))
        self.cancelButton.setStyleSheet(_translate("MainWindow", "background-color: #e74c3c; color: white; border-radius: 8px; font-size: 16px; padding: 12px; border: none; margin-top: 10px;"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.registerTab), _translate("MainWindow", "注册"))

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())