# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainInterface(object):
    def setupUi(self, MainInterface):
        MainInterface.setObjectName("MainInterface")
        MainInterface.resize(1062, 602)
        self.centralwidget = QtWidgets.QWidget(MainInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.profileManagementButton = QtWidgets.QPushButton(self.centralwidget)
        self.profileManagementButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileManagementButton.setObjectName("profileManagementButton")
        self.gridLayout.addWidget(self.profileManagementButton, 1, 0, 1, 1)
        self.orderchangebutton = QtWidgets.QPushButton(self.centralwidget)
        self.orderchangebutton.setObjectName("orderchangebutton")
        self.gridLayout.addWidget(self.orderchangebutton, 1, 1, 1, 1)
        self.InsertAndDeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.InsertAndDeleteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.InsertAndDeleteButton.setObjectName("InsertAndDeleteButton")
        self.gridLayout.addWidget(self.InsertAndDeleteButton, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 3)
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcomeLabel.sizePolicy().hasHeightForWidth())
        self.welcomeLabel.setSizePolicy(sizePolicy)
        self.welcomeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.welcomeLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.gridLayout.addWidget(self.welcomeLabel, 0, 0, 1, 3)
        MainInterface.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainInterface)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1062, 22))
        self.menuBar.setObjectName("menuBar")
        MainInterface.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainInterface)
        self.statusBar.setObjectName("statusBar")
        MainInterface.setStatusBar(self.statusBar)

        self.retranslateUi(MainInterface)
        QtCore.QMetaObject.connectSlotsByName(MainInterface)

    def retranslateUi(self, MainInterface):
        _translate = QtCore.QCoreApplication.translate
        MainInterface.setStyleSheet(_translate("MainInterface", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003D79;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}"))
        self.profileManagementButton.setText(_translate("MainInterface", "修改用户信息"))
        self.orderchangebutton.setText(_translate("MainInterface", "修改订单信息"))
        self.InsertAndDeleteButton.setText(_translate("MainInterface", "航班信息查改"))
        self.pushButton.setText(_translate("MainInterface", "退出登录"))
        self.welcomeLabel.setText(_translate("MainInterface", "## 管理员控制面板"))
