# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainInterface(object):
    def setupUi(self, MainInterface):
        MainInterface.setObjectName("MainInterface")
        MainInterface.resize(992, 602)
        self.centralwidget = QtWidgets.QWidget(MainInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.welcomeLabel = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.gridLayout.addWidget(self.welcomeLabel, 0, 0, 1, 2)
        self.profileManagementButton = QtWidgets.QPushButton(self.centralwidget)
        self.profileManagementButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.profileManagementButton.setObjectName("profileManagementButton")
        self.gridLayout.addWidget(self.profileManagementButton, 0, 2, 1, 1)
        self.commentManagementButton = QtWidgets.QPushButton(self.centralwidget)
        self.commentManagementButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.commentManagementButton.setObjectName("commentManagementButton")
        self.gridLayout.addWidget(self.commentManagementButton, 0, 3, 1, 1)
        self.games = QtWidgets.QPushButton(self.centralwidget)
        self.games.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.games.setObjectName("games")
        self.gridLayout.addWidget(self.games, 1, 0, 1, 1)
        self.flightRecommendationButton = QtWidgets.QPushButton(self.centralwidget)
        self.flightRecommendationButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flightRecommendationButton.setObjectName("flightRecommendationButton")
        self.gridLayout.addWidget(self.flightRecommendationButton, 1, 1, 1, 2)
        self.flightSearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.flightSearchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flightSearchButton.setObjectName("flightSearchButton")
        self.gridLayout.addWidget(self.flightSearchButton, 1, 3, 1, 1)
        self.flightSortButton = QtWidgets.QPushButton(self.centralwidget)
        self.flightSortButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.flightSortButton.setObjectName("flightSortButton")
        self.gridLayout.addWidget(self.flightSortButton, 2, 0, 1, 1)
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout.setObjectName("logout")
        self.gridLayout.addWidget(self.logout, 2, 3, 1, 1)
        self.about = QtWidgets.QPushButton(self.centralwidget)
        self.about.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about.setObjectName("about")
        self.gridLayout.addWidget(self.about, 2, 1, 1, 2)
        MainInterface.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainInterface)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 992, 22))
        self.menuBar.setObjectName("menuBar")
        MainInterface.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainInterface)
        self.statusBar.setObjectName("statusBar")
        MainInterface.setStatusBar(self.statusBar)

        self.retranslateUi(MainInterface)
        QtCore.QMetaObject.connectSlotsByName(MainInterface)

    def retranslateUi(self, MainInterface):
        _translate = QtCore.QCoreApplication.translate
        MainInterface.setStyleSheet(_translate("MainInterface", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003D79;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}"))
        self.welcomeLabel.setText(_translate("MainInterface", "欢迎使用航班管理系统"))
        self.profileManagementButton.setText(_translate("MainInterface", "个人信息管理"))
        self.commentManagementButton.setText(_translate("MainInterface", "评论管理"))
        self.games.setText(_translate("MainInterface", "等累了吗？来玩点好玩的"))
        self.flightRecommendationButton.setText(_translate("MainInterface", "航班推荐"))
        self.flightSearchButton.setText(_translate("MainInterface", "航班搜索"))
        self.flightSortButton.setText(_translate("MainInterface", "航班排序"))
        self.logout.setText(_translate("MainInterface", "退出登录"))
        self.about.setText(_translate("MainInterface", "关于"))
