# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainInterface(object):
    def setupUi(self, MainInterface):
        MainInterface.setObjectName("MainInterface")
        MainInterface.resize(1292, 602)
        self.centralwidget = QtWidgets.QWidget(MainInterface)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 70, 941, 401))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.orderManagementButton = QtWidgets.QPushButton(self.widget)
        self.orderManagementButton.setObjectName("orderManagementButton")
        self.gridLayout.addWidget(self.orderManagementButton, 4, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 1, 1, 1)
        self.flightSortButton = QtWidgets.QPushButton(self.widget)
        self.flightSortButton.setObjectName("flightSortButton")
        self.gridLayout.addWidget(self.flightSortButton, 4, 0, 1, 1)
        self.welcomeLabel = QtWidgets.QLabel(self.widget)
        self.welcomeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.gridLayout.addWidget(self.welcomeLabel, 0, 0, 1, 2)
        self.flightRecommendationButton = QtWidgets.QPushButton(self.widget)
        self.flightRecommendationButton.setObjectName("flightRecommendationButton")
        self.gridLayout.addWidget(self.flightRecommendationButton, 2, 1, 1, 1)
        self.commentManagementButton = QtWidgets.QPushButton(self.widget)
        self.commentManagementButton.setObjectName("commentManagementButton")
        self.gridLayout.addWidget(self.commentManagementButton, 0, 3, 1, 1)
        self.flightDetailsButton = QtWidgets.QPushButton(self.widget)
        self.flightDetailsButton.setObjectName("flightDetailsButton")
        self.gridLayout.addWidget(self.flightDetailsButton, 2, 0, 1, 1)
        self.profileManagementButton = QtWidgets.QPushButton(self.widget)
        self.profileManagementButton.setObjectName("profileManagementButton")
        self.gridLayout.addWidget(self.profileManagementButton, 0, 2, 1, 1)
        self.flightSearchButton = QtWidgets.QPushButton(self.widget)
        self.flightSearchButton.setObjectName("flightSearchButton")
        self.gridLayout.addWidget(self.flightSearchButton, 2, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 3, 1, 1)
        MainInterface.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainInterface)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1292, 22))
        self.menuBar.setObjectName("menuBar")
        MainInterface.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainInterface)
        self.statusBar.setObjectName("statusBar")
        MainInterface.setStatusBar(self.statusBar)

        self.retranslateUi(MainInterface)
        QtCore.QMetaObject.connectSlotsByName(MainInterface)

    def retranslateUi(self, MainInterface):
        _translate = QtCore.QCoreApplication.translate
        MainInterface.setStyleSheet(_translate("MainInterface", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #003D79;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}"))
        self.orderManagementButton.setText(_translate("MainInterface", "订单管理"))
        self.pushButton_2.setText(_translate("MainInterface", "关于"))
        self.flightSortButton.setText(_translate("MainInterface", "航班排序"))
        self.welcomeLabel.setText(_translate("MainInterface", "欢迎使用航班管理系统"))
        self.flightRecommendationButton.setText(_translate("MainInterface", "航班推荐"))
        self.commentManagementButton.setText(_translate("MainInterface", "评论管理"))
        self.flightDetailsButton.setText(_translate("MainInterface", "航班详情"))
        self.profileManagementButton.setText(_translate("MainInterface", "个人信息管理"))
        self.flightSearchButton.setText(_translate("MainInterface", "航班搜索"))
        self.pushButton.setText(_translate("MainInterface", "退出登录"))
        self.pushButton_3.setText(_translate("MainInterface", "管理员控制面板"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainInterface = QtWidgets.QMainWindow()
    ui = Ui_MainInterface()
    ui.setupUi(MainInterface)
    MainInterface.show()
    sys.exit(app.exec_())