# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manager.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminDashboardWindow(object):
    def setupUi(self, AdminDashboardWindow):
        AdminDashboardWindow.setObjectName("AdminDashboardWindow")
        AdminDashboardWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(AdminDashboardWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.adminTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.adminTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adminTitleLabel.setObjectName("adminTitleLabel")
        self.verticalLayout.addWidget(self.adminTitleLabel)
        self.ordersLabel = QtWidgets.QLabel(self.centralwidget)
        self.ordersLabel.setObjectName("ordersLabel")
        self.verticalLayout.addWidget(self.ordersLabel)
        self.ordersTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.ordersTableWidget.setColumnCount(5)
        self.ordersTableWidget.setProperty("horizontalHeaderLabels", ['订单号', '用户名', '航班号', '座位号', '状态'])
        self.ordersTableWidget.setObjectName("ordersTableWidget")
        self.ordersTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.ordersTableWidget)
        self.ordersButtonLayout = QtWidgets.QHBoxLayout()
        self.ordersButtonLayout.setObjectName("ordersButtonLayout")
        self.editOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.editOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editOrderButton.setObjectName("editOrderButton")
        self.ordersButtonLayout.addWidget(self.editOrderButton)
        self.verticalLayout.addLayout(self.ordersButtonLayout)
        self.usersLabel = QtWidgets.QLabel(self.centralwidget)
        self.usersLabel.setObjectName("usersLabel")
        self.verticalLayout.addWidget(self.usersLabel)
        self.usersTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.usersTableWidget.setColumnCount(4)
        self.usersTableWidget.setProperty("horizontalHeaderLabels", ['用户名', '邮箱', '手机号', '注册日期'])
        self.usersTableWidget.setObjectName("usersTableWidget")
        self.usersTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.usersTableWidget)
        self.usersButtonLayout = QtWidgets.QHBoxLayout()
        self.usersButtonLayout.setObjectName("usersButtonLayout")
        self.editUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.editUserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editUserButton.setObjectName("editUserButton")
        self.usersButtonLayout.addWidget(self.editUserButton)
        self.verticalLayout.addLayout(self.usersButtonLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.backToPreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToPreviousButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToPreviousButton.setObjectName("backToPreviousButton")
        self.buttonLayout.addWidget(self.backToPreviousButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        AdminDashboardWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminDashboardWindow)
        QtCore.QMetaObject.connectSlotsByName(AdminDashboardWindow)

    def retranslateUi(self, AdminDashboardWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminDashboardWindow.setStyleSheet(_translate("AdminDashboardWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}"))
        self.adminTitleLabel.setStyleSheet(_translate("AdminDashboardWindow", "font-size: 20px; font-weight: bold; color: #333;"))
        self.adminTitleLabel.setText(_translate("AdminDashboardWindow", "管理员控制面板"))
        self.ordersLabel.setText(_translate("AdminDashboardWindow", "所有订单："))
        self.editOrderButton.setText(_translate("AdminDashboardWindow", "修改订单信息"))
        self.usersLabel.setText(_translate("AdminDashboardWindow", "所有用户："))
        self.editUserButton.setText(_translate("AdminDashboardWindow", "修改用户信息"))
        self.backToPreviousButton.setText(_translate("AdminDashboardWindow", "返回上一页"))
