# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderManagementWindow(object):
    def setupUi(self, OrderManagementWindow):
        OrderManagementWindow.setObjectName("OrderManagementWindow")
        OrderManagementWindow.resize(800, 561)
        self.centralwidget = QtWidgets.QWidget(OrderManagementWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.orderTable = QtWidgets.QTableWidget(self.centralwidget)
        self.orderTable.setRowCount(0)
        self.orderTable.setColumnCount(13)
        self.orderTable.setProperty("horizontalHeaderLabels", ['订单号', '用户名', '航班号', '座位号'])
        self.orderTable.setObjectName("orderTable")
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderTable.setHorizontalHeaderItem(8, item)
        self.verticalLayout.addWidget(self.orderTable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        self.cancelOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelOrderButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelOrderButton.setObjectName("cancelOrderButton")
        self.buttonLayout.addWidget(self.cancelOrderButton)
        self.backToMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToMainButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToMainButton.setObjectName("backToMainButton")
        self.buttonLayout.addWidget(self.backToMainButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        OrderManagementWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderManagementWindow)

    def retranslateUi(self, OrderManagementWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderManagementWindow.setStyleSheet(_translate("OrderManagementWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader::section {\n"
"    border: 1px solid #ccc;\n"
"    border-style: none;\n"
"}"))
        item = self.orderTable.horizontalHeaderItem(0)
        item.setText(_translate("OrderManagementWindow", "订单"))
        item = self.orderTable.horizontalHeaderItem(1)
        item.setText(_translate("OrderManagementWindow", "名称"))
        item = self.orderTable.horizontalHeaderItem(2)
        item.setText(_translate("OrderManagementWindow", "航班号"))
        item = self.orderTable.horizontalHeaderItem(3)
        item.setText(_translate("OrderManagementWindow", "起飞时间"))
        item = self.orderTable.horizontalHeaderItem(4)
        item.setText(_translate("OrderManagementWindow", "降落时间"))
        item = self.orderTable.horizontalHeaderItem(5)
        item.setText(_translate("OrderManagementWindow", "目的地"))
        item = self.orderTable.horizontalHeaderItem(6)
        item.setText(_translate("OrderManagementWindow", "航司"))
        item = self.orderTable.horizontalHeaderItem(7)
        item.setText(_translate("OrderManagementWindow", "价格"))
        item = self.orderTable.horizontalHeaderItem(8)
        item.setText(_translate("OrderManagementWindow", "座位号"))
        self.cancelOrderButton.setText(_translate("OrderManagementWindow", "取消订单"))
        self.backToMainButton.setText(_translate("OrderManagementWindow", "返回主界面"))
