# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderDetailsWindow(object):
    def setupUi(self, OrderDetailsWindow):
        OrderDetailsWindow.setObjectName("OrderDetailsWindow")
        OrderDetailsWindow.resize(598, 407)
        self.centralwidget = QtWidgets.QWidget(OrderDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.orderDetailsLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderDetailsLabel.sizePolicy().hasHeightForWidth())
        self.orderDetailsLabel.setSizePolicy(sizePolicy)
        self.orderDetailsLabel.setObjectName("orderDetailsLabel")
        self.verticalLayout_2.addWidget(self.orderDetailsLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.companyLabel = QtWidgets.QLabel(self.centralwidget)
        self.companyLabel.setObjectName("companyLabel")
        self.verticalLayout.addWidget(self.companyLabel)
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel)
        self.flightNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.flightNumberLabel.setObjectName("flightNumberLabel")
        self.verticalLayout.addWidget(self.flightNumberLabel)
        self.departureLabel = QtWidgets.QLabel(self.centralwidget)
        self.departureLabel.setObjectName("departureLabel")
        self.verticalLayout.addWidget(self.departureLabel)
        self.destinationLabel = QtWidgets.QLabel(self.centralwidget)
        self.destinationLabel.setObjectName("destinationLabel")
        self.verticalLayout.addWidget(self.destinationLabel)
        self.priceLabel = QtWidgets.QLabel(self.centralwidget)
        self.priceLabel.setObjectName("priceLabel")
        self.verticalLayout.addWidget(self.priceLabel)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.buttonLayout.addWidget(self.pushButton)
        self.backToPreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToPreviousButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backToPreviousButton.setObjectName("backToPreviousButton")
        self.buttonLayout.addWidget(self.backToPreviousButton)
        self.verticalLayout_2.addLayout(self.buttonLayout)
        OrderDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderDetailsWindow)

    def retranslateUi(self, OrderDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderDetailsWindow.setStyleSheet(_translate("OrderDetailsWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
".\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}"))
        self.orderDetailsLabel.setText(_translate("OrderDetailsWindow", "订单详情"))
        self.companyLabel.setText(_translate("OrderDetailsWindow", "航司：123"))
        self.usernameLabel.setText(_translate("OrderDetailsWindow", "用户名: user01"))
        self.flightNumberLabel.setText(_translate("OrderDetailsWindow", "航班号: ABC123"))
        self.departureLabel.setText(_translate("OrderDetailsWindow", "出发地: 北京"))
        self.destinationLabel.setText(_translate("OrderDetailsWindow", "目的地: 上海"))
        self.priceLabel.setText(_translate("OrderDetailsWindow", "价格: ¥500"))
        self.statusLabel.setText(_translate("OrderDetailsWindow", "订单状态: 已支付"))
        self.pushButton.setText(_translate("OrderDetailsWindow", "支付下单"))
        self.backToPreviousButton.setText(_translate("OrderDetailsWindow", "返回上一页"))
