# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderDetailsWindow(object):
    def setupUi(self, OrderDetailsWindow):
        OrderDetailsWindow.setObjectName("OrderDetailsWindow")
        OrderDetailsWindow.resize(800, 602)
        self.centralwidget = QtWidgets.QWidget(OrderDetailsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.orderDetailsLabel = QtWidgets.QLabel(self.centralwidget)
        self.orderDetailsLabel.setObjectName("orderDetailsLabel")
        self.verticalLayout.addWidget(self.orderDetailsLabel)
        self.orderInfoLayout = QtWidgets.QVBoxLayout()
        self.orderInfoLayout.setObjectName("orderInfoLayout")
        self.orderNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.orderNumberLabel.setObjectName("orderNumberLabel")
        self.orderInfoLayout.addWidget(self.orderNumberLabel)
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.orderInfoLayout.addWidget(self.usernameLabel)
        self.flightNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.flightNumberLabel.setObjectName("flightNumberLabel")
        self.orderInfoLayout.addWidget(self.flightNumberLabel)
        self.departureLabel = QtWidgets.QLabel(self.centralwidget)
        self.departureLabel.setObjectName("departureLabel")
        self.orderInfoLayout.addWidget(self.departureLabel)
        self.destinationLabel = QtWidgets.QLabel(self.centralwidget)
        self.destinationLabel.setObjectName("destinationLabel")
        self.orderInfoLayout.addWidget(self.destinationLabel)
        self.seatNumberLabel = QtWidgets.QLabel(self.centralwidget)
        self.seatNumberLabel.setObjectName("seatNumberLabel")
        self.orderInfoLayout.addWidget(self.seatNumberLabel)
        self.priceLabel = QtWidgets.QLabel(self.centralwidget)
        self.priceLabel.setObjectName("priceLabel")
        self.orderInfoLayout.addWidget(self.priceLabel)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setObjectName("statusLabel")
        self.orderInfoLayout.addWidget(self.statusLabel)
        self.verticalLayout.addLayout(self.orderInfoLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.backToPreviousButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToPreviousButton.setObjectName("backToPreviousButton")
        self.buttonLayout.addWidget(self.backToPreviousButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        OrderDetailsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderDetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderDetailsWindow)

    def retranslateUi(self, OrderDetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderDetailsWindow.setStyleSheet(_translate("OrderDetailsWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}"))
        self.orderDetailsLabel.setText(_translate("OrderDetailsWindow", "订单详情"))
        self.orderNumberLabel.setText(_translate("OrderDetailsWindow", "订单号: 123456"))
        self.usernameLabel.setText(_translate("OrderDetailsWindow", "用户名: user01"))
        self.flightNumberLabel.setText(_translate("OrderDetailsWindow", "航班号: ABC123"))
        self.departureLabel.setText(_translate("OrderDetailsWindow", "出发地: 北京"))
        self.destinationLabel.setText(_translate("OrderDetailsWindow", "目的地: 上海"))
        self.seatNumberLabel.setText(_translate("OrderDetailsWindow", "座位号: 12A"))
        self.priceLabel.setText(_translate("OrderDetailsWindow", "价格: ¥500"))
        self.statusLabel.setText(_translate("OrderDetailsWindow", "订单状态: 已支付"))
        self.backToPreviousButton.setText(_translate("OrderDetailsWindow", "返回上一页"))
