# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_management.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrderManagementWindow(object):
    def setupUi(self, OrderManagementWindow):
        OrderManagementWindow.setObjectName("OrderManagementWindow")
        OrderManagementWindow.resize(800, 602)
        self.centralwidget = QtWidgets.QWidget(OrderManagementWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.orderTable = QtWidgets.QTableWidget(self.centralwidget)
        self.orderTable.setRowCount(0)
        self.orderTable.setColumnCount(4)
        self.orderTable.setProperty("horizontalHeaderLabels", ['订单号', '用户名', '航班号', '座位号'])
        self.orderTable.setObjectName("orderTable")
        self.verticalLayout.addWidget(self.orderTable)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setSpacing(10)
        self.buttonLayout.setObjectName("buttonLayout")
        self.createOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.createOrderButton.setObjectName("createOrderButton")
        self.buttonLayout.addWidget(self.createOrderButton)
        self.cancelOrderButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelOrderButton.setObjectName("cancelOrderButton")
        self.buttonLayout.addWidget(self.cancelOrderButton)
        self.backToMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToMainButton.setObjectName("backToMainButton")
        self.buttonLayout.addWidget(self.backToMainButton)
        self.verticalLayout.addLayout(self.buttonLayout)
        OrderManagementWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(OrderManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(OrderManagementWindow)

    def retranslateUi(self, OrderManagementWindow):
        _translate = QtCore.QCoreApplication.translate
        OrderManagementWindow.setStyleSheet(_translate("OrderManagementWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader::section {\n"
"    border: 1px solid #ccc;\n"
"    border-style: none;\n"
"}"))
        self.createOrderButton.setText(_translate("OrderManagementWindow", "创建订单"))
        self.cancelOrderButton.setText(_translate("OrderManagementWindow", "取消订单"))
        self.backToMainButton.setText(_translate("OrderManagementWindow", "返回主界面"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrderManagementWindow = QtWidgets.QMainWindow()
    ui = Ui_OrderManagementWindow()
    ui.setupUi(OrderManagementWindow)
    OrderManagementWindow.show()
    sys.exit(app.exec_())