# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfileManagementWindow(object):
    def setupUi(self, ProfileManagementWindow):
        ProfileManagementWindow.setObjectName("ProfileManagementWindow")
        ProfileManagementWindow.resize(489, 430)
        self.centralwidget = QtWidgets.QWidget(ProfileManagementWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.profileTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.profileTitleLabel.setObjectName("profileTitleLabel")
        self.gridLayout.addWidget(self.profileTitleLabel, 0, 0, 1, 1)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setStyleSheet("QLabel {\n"
"    color: red;\n"
"}\n"
"")
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout.addWidget(self.statusLabel, 2, 1, 1, 1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteButton.setObjectName("deleteButton")
        self.buttonLayout.addWidget(self.deleteButton)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setObjectName("backButton")
        self.buttonLayout.addWidget(self.backButton)
        self.gridLayout.addLayout(self.buttonLayout, 3, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        ProfileManagementWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProfileManagementWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileManagementWindow)

    def retranslateUi(self, ProfileManagementWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfileManagementWindow.setStyleSheet(_translate("ProfileManagementWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 150px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"    padding: 10px;\n"
"}"))
        self.profileTitleLabel.setText(_translate("ProfileManagementWindow", "个人信息管理面板"))
        self.deleteButton.setText(_translate("ProfileManagementWindow", "删除"))
        self.backButton.setText(_translate("ProfileManagementWindow", "返回主菜单"))
