# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sort_flights.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FlightSortWindow(object):
    def setupUi(self, FlightSortWindow):
        FlightSortWindow.setObjectName("FlightSortWindow")
        FlightSortWindow.resize(800, 591)
        self.centralwidget = QtWidgets.QWidget(FlightSortWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sortCriteriaLabel = QtWidgets.QLabel(self.centralwidget)
        self.sortCriteriaLabel.setObjectName("sortCriteriaLabel")
        self.horizontalLayout.addWidget(self.sortCriteriaLabel)
        self.sortCriteriaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.sortCriteriaComboBox.setObjectName("sortCriteriaComboBox")
        self.sortCriteriaComboBox.addItem("")
        self.sortCriteriaComboBox.addItem("")
        self.horizontalLayout.addWidget(self.sortCriteriaComboBox)
        self.backToMainButton = QtWidgets.QPushButton(self.centralwidget)
        self.backToMainButton.setObjectName("backToMainButton")
        self.horizontalLayout.addWidget(self.backToMainButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sortButton = QtWidgets.QPushButton(self.centralwidget)
        self.sortButton.setObjectName("sortButton")
        self.verticalLayout.addWidget(self.sortButton)
        self.sortedFlightTable = QtWidgets.QTableWidget(self.centralwidget)
        self.sortedFlightTable.setRowCount(0)
        self.sortedFlightTable.setColumnCount(5)
        self.sortedFlightTable.setProperty("horizontalHeaderLabels", ['航班号 ✈️', '出发地 🌍', '目的地 🏝️', '出发时间 ⏰', '剩余座位 🪑'])
        self.sortedFlightTable.setObjectName("sortedFlightTable")
        self.verticalLayout.addWidget(self.sortedFlightTable)
        FlightSortWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(FlightSortWindow)
        QtCore.QMetaObject.connectSlotsByName(FlightSortWindow)

    def retranslateUi(self, FlightSortWindow):
        _translate = QtCore.QCoreApplication.translate
        FlightSortWindow.setStyleSheet(_translate("FlightSortWindow", "QMainWindow {\n"
"    background-color: #F5F5F5;\n"
"    font-family: \'Segoe UI\', sans-serif;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #0078D7;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #005FAC;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    border: 1px solid #ccc;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 5px;\n"
"    border-bottom: 1px solid #ccc;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: #0078D7;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::horizontalHeader::section {\n"
"    border: 1px solid #ccc;\n"
"    border-style: none;\n"
"}"))
        self.sortCriteriaLabel.setText(_translate("FlightSortWindow", "排序条件 🏷️"))
        self.sortCriteriaComboBox.setProperty("placeholderText", _translate("FlightSortWindow", "选择排序条件"))
        self.sortCriteriaComboBox.setItemText(0, _translate("FlightSortWindow", "价格 💰"))
        self.sortCriteriaComboBox.setItemText(1, _translate("FlightSortWindow", "时间 ⏰"))
        self.backToMainButton.setText(_translate("FlightSortWindow", "返回主界面"))
        self.sortButton.setText(_translate("FlightSortWindow", "排序 🔄"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FlightSortWindow = QtWidgets.QMainWindow()
    ui = Ui_FlightSortWindow()
    ui.setupUi(FlightSortWindow)
    FlightSortWindow.show()
    sys.exit(app.exec_())
    FlightSortWindow.close()
    sys.exit(0)
